### ISSUE TITLE
Exception with message 'Undefined index: headers'

### ISSUE THREAD

**Issue by dmftaras** [F21/DNSMadeEasy#8]
Hi,
I'm getting this error when trying to create multiple subdomains in one request

e.g.
`
$client->records()->add($domainID, $config)
`

In the end domains got created in DnsMadeEasy, but I'm getting following response:

in /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/Response.php:124

Stack trace:
#0 /var/www/html/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/c...', 124, Array)
#1 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/Response.php(124): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/c...', 124, Array)
#2 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/REST.php(187): DNSMadeEasy\driver\Response->__construct('HTTP/1.1 100 Co...', 0.671352)
#3 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/REST.php(73): DNSMadeEasy\driver\REST->send('/dns/managed/61...', Array, 'post', Array)
#4 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/resource/Records.php(79): DNSMadeEasy\driver\REST->post('/dns/managed/61...', Array)
#5 /var/www/html/common/components/DnsComponent.php(104): DNSMadeEasy\resource\Records->add(6124999, Array)
#6 /var/www/html/common/models/internal/DomainsQueue.php(95): common\components\DnsComponent->createRecords(6124999, Array)
#7 /var/www/html/console/controllers/WorkerController.php(164): common\models\internal\DomainsQueue::proceedBatch()
#8 [internal function]: console\controllers\WorkerController->actionProceedDmeRecords()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('proceed-dme-rec...', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('proceed-dme-rec...', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('worker/proceed-...', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('worker/proceed-...', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /var/www/html/yii(31): yii\base\Application->run()
#17 {main}

**Comment by F21** [comment]
Can you post the full error message?

**Comment by dmftaras** [comment]
just noticed that it works fine if I pass like 10 records at the same time, but when I do 100:

This is the response:
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: headers'

in /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/Response.php:124

Stack trace:
#0 /var/www/html/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/c...', 124, Array)
#1 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/Response.php(124): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/c...', 124, Array)
#2 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/REST.php(186): DNSMadeEasy\driver\Response->__construct('HTTP/1.1 100 Co...', 0.87898)
#3 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/driver/REST.php(73): DNSMadeEasy\driver\REST->send('/dns/managed/61...', Array, 'post', Array)
#4 /var/www/html/vendor/f21/dnsmadeeasy/DNSMadeEasy/resource/Records.php(79): DNSMadeEasy\driver\REST->post('/dns/managed/61...', Array)
#5 /var/www/html/common/components/DnsComponent.php(104): DNSMadeEasy\resource\Records->add(6124999, Array)
#6 /var/www/html/common/models/internal/DomainsQueue.php(95): common\components\DnsComponent->createRecords(6124999, Array)
#7 /var/www/html/console/controllers/WorkerController.php(164): common\models\internal\DomainsQueue::proceedBatch()
#8 [internal function]: console\controllers\WorkerController->actionProceedDmeRecords()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('proceed-dme-rec...', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('proceed-dme-rec...', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('worker/proceed-...', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('worker/proceed-...', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /var/www/html/yii(31): yii\base\Application->run()
#17 {main}


And this is value of $parsed variable in f21/dnsmadeeasy/DNSMadeEasy/driver/Response.php
array(2) {
  ["headers"]=>
  string(21) "HTTP/1.1 100 Continue"
  ["body"]=>
  string(21764) "HTTP/1.1 201 Created
Server: Apache-Coyote/1.1
x-dnsme-requestId: 8d8f0984-7ea9-4bd5-a1c7-9d403991f811
x-dnsme-requestsRemaining: 146
x-dnsme-requestLimit: 150
Set-Cookie: JSESSIONID=7B43E165061FE278E5C2D3840F3A1749; Path=/V2.0; Secure; HttpOnly
Location: https://api.dnsmadeeasy.com/V2.0/dns/managed/6124999/records/createMulti/6124999
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 05 Jun 2019 08:53:03 GMT

[{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-0","value":"66.228.41.244","id":90129967,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-1","value":"66.228.41.244","id":90129965,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-2","value":"66.228.41.244","id":90129966,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-3","value":"66.228.41.244","id":90129963,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-4","value":"66.228.41.244","id":90129964,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-5","value":"66.228.41.244","id":90129961,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-6","value":"66.228.41.244","id":90129962,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-7","value":"66.228.41.244","id":90129935,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-8","value":"66.228.41.244","id":90129933,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-9","value":"66.228.41.244","id":90129938,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-10","value":"66.228.41.244","id":90129929,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-11","value":"66.228.41.244","id":90129931,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-12","value":"66.228.41.244","id":90129926,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-13","value":"66.228.41.244","id":90129927,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-14","value":"66.228.41.244","id":90129923,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-15","value":"66.228.41.244","id":90129925,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-16","value":"66.228.41.244","id":90129919,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-17","value":"66.228.41.244","id":90129921,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-18","value":"66.228.41.244","id":90129940,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-19","value":"66.228.41.244","id":90129939,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-20","value":"66.228.41.244","id":90129912,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-21","value":"66.228.41.244","id":90129906,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-22","value":"66.228.41.244","id":90129907,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-23","value":"66.228.41.244","id":90129909,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-24","value":"66.228.41.244","id":90129910,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-25","value":"66.228.41.244","id":90129899,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-26","value":"66.228.41.244","id":90129901,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-27","value":"66.228.41.244","id":90129903,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-28","value":"66.228.41.244","id":90129905,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-29","value":"66.228.41.244","id":90129917,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-30","value":"66.228.41.244","id":90129892,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-31","value":"66.228.41.244","id":90129893,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-32","value":"66.228.41.244","id":90129890,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-33","value":"66.228.41.244","id":90129891,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-34","value":"66.228.41.244","id":90129887,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-35","value":"66.228.41.244","id":90129889,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-36","value":"66.228.41.244","id":90129883,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-37","value":"66.228.41.244","id":90129885,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-38","value":"66.228.41.244","id":90129879,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-39","value":"66.228.41.244","id":90129881,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-40","value":"66.228.41.244","id":90129958,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-41","value":"66.228.41.244","id":90129959,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-42","value":"66.228.41.244","id":90129960,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-43","value":"66.228.41.244","id":90129942,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-44","value":"66.228.41.244","id":90129943,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-45","value":"66.228.41.244","id":90129945,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-46","value":"66.228.41.244","id":90129947,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-47","value":"66.228.41.244","id":90129949,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-48","value":"66.228.41.244","id":90129951,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-49","value":"66.228.41.244","id":90129953,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-50","value":"66.228.41.244","id":90129936,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-51","value":"66.228.41.244","id":90129937,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-52","value":"66.228.41.244","id":90129932,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-53","value":"66.228.41.244","id":90129934,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-54","value":"66.228.41.244","id":90129922,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-55","value":"66.228.41.244","id":90129924,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-56","value":"66.228.41.244","id":90129918,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-57","value":"66.228.41.244","id":90129920,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-58","value":"66.228.41.244","id":90129928,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-59","value":"66.228.41.244","id":90129930,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-60","value":"66.228.41.244","id":90129908,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-61","value":"66.228.41.244","id":90129900,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-62","value":"66.228.41.244","id":90129898,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-63","value":"66.228.41.244","id":90129904,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-64","value":"66.228.41.244","id":90129902,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-65","value":"66.228.41.244","id":90129914,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-66","value":"66.228.41.244","id":90129913,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-67","value":"66.228.41.244","id":90129916,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-68","value":"66.228.41.244","id":90129915,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-69","value":"66.228.41.244","id":90129911,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-70","value":"66.228.41.244","id":90129888,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-71","value":"66.228.41.244","id":90129886,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-72","value":"66.228.41.244","id":90129884,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-73","value":"66.228.41.244","id":90129882,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-74","value":"66.228.41.244","id":90129880,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-75","value":"66.228.41.244","id":90129878,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-76","value":"66.228.41.244","id":90129897,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-77","value":"66.228.41.244","id":90129896,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-78","value":"66.228.41.244","id":90129895,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-79","value":"66.228.41.244","id":90129894,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-80","value":"66.228.41.244","id":90129941,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-81","value":"66.228.41.244","id":90129946,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-82","value":"66.228.41.244","id":90129944,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-83","value":"66.228.41.244","id":90129950,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-84","value":"66.228.41.244","id":90129948,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-85","value":"66.228.41.244","id":90129954,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-86","value":"66.228.41.244","id":90129952,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-87","value":"66.228.41.244","id":90129956,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-88","value":"66.228.41.244","id":90129955,"type":"A"},{"source":1,"ttl":86400,"gtdLocation":"DEFAULT","sourceId":6124999,"failover":false,"monitor":false,"hardLink":false,"dynamicDns":true,"failed":false,"name":"t3st1ng-batch-1559724778-89","value":"66.228.41.244","id":90129957,"type":"A"}]"
}

**Comment by F21** [comment]
Can you print the value of `$parsedHeaders` here: https://github.com/F21/DNSMadeEasy/blob/master/DNSMadeEasy/driver/Response.php#L120

My suspicion is that because there is only 1 line in the headers, the `headers` element is never created: https://sourcegraph.com/github.com/F21/DNSMadeEasy@166b8eac312764d89172f4cfb30365e612af09f8/-/blob/DNSMadeEasy/driver/Response.php#L243

It's been a while since I've used DNSMadeEasy or written PHP code, but I don't think I ever received a HTTP 100 response when testing or using the package.

My suggest would be to add a check here: https://github.com/F21/DNSMadeEasy/blob/master/DNSMadeEasy/driver/Response.php#L124 to set `$_headers` if `$parsedHeaders['headers'];` exists. 

If you'd like to open a PR for it, I would be happy to merge it in.

**Comment by dmftaras** [comment]
@F21 could you make a new release which includes this fix, so that we can use it in production? 
thanks

**Comment by F21** [comment]
@dmftaras Just tagged 1.0.6.
